stages:
  data_split:
    cmd: python src/data_split.py
    deps:
    - data/pool_data
    - src/data_split.py
    params:
    - base
    - data_split
    outs:
    - data/test_data
    - data/train_data
  train:
    cmd: python src/train.py ${base} ${train}
    deps:
    - data/train_data
    - src/train.py
    outs:
    - models/model.pkl
    - models/model.pth
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/test_data
    - models/model.pkl
    - src/evaluate.py
    params:
    - base
    - evaluate